In [1]:
import tmdbsimple as tmdb
tmdb.API_KEY = '9261f98fe849c886c321d275f6372e3c'

In [2]:
import requests

In [5]:
    >>> movie = tmdb.Movies(262391)
    >>> response = movie.info()
    >>> movie.title
    'The Matrix'
    >>> movie.genres

[{'id': 35, 'name': 'Comedy'}]

In [6]:
response

{'adult': False,
 'backdrop_path': '/xSTedn34WWuOk5V60UK3ZXWwkXz.jpg',
 'belongs_to_collection': {'id': 579870,
  'name': 'Serial (Bad) Weddings Collection',
  'poster_path': '/2y94JZNclwGfzv9X5NdT1aiRPB6.jpg',
  'backdrop_path': '/c28WVrY7EWd5LlJPgaXxL186tHt.jpg'},
 'budget': 13000000,
 'genres': [{'id': 35, 'name': 'Comedy'}],
 'homepage': '',
 'id': 262391,
 'imdb_id': 'tt2800240',
 'original_language': 'fr',
 'original_title': "Qu'est-ce qu'on a fait au Bon Dieu",
 'overview': 'A catholic French couple sees their life upside down when their four daughters get married to men of different religion and origins.',
 'popularity': 19.852,
 'poster_path': '/5Hw0GuPahcTCMsJNaLn37OVeXB3.jpg',
 'production_companies': [{'id': 581,
   'logo_path': '/pzJLNyKypqwAgLR4OjmaxA5WEjm.png',
   'name': 'UGC',
   'origin_country': 'FR'}],
 'production_countries': [{'iso_3166_1': 'FR', 'name': 'France'}],
 'release_date': '2014-04-16',
 'revenue': 176404493,
 'runtime': 94,
 'spoken_languages': [{'english_name': 'French',
   'iso_639_1': 'fr',
   'name': 'Fran√ßais'}],
 'status': 'Released',
 'tagline': '4 marriages, 2 long-faces',
 'title': 'Serial (Bad) Weddings',
 'video': False,
 'vote_average': 6.7,
 'vote_count': 3019}

In [38]:
response['id']

77338

In [10]:
response['genres']

[{'id': 28, 'name': 'Action'}, {'id': 878, 'name': 'Science Fiction'}]

In [27]:
tmdb_id=[77338.0, 262391.0, 140607.0, 420818.0, 52077.0, 304410.0, 304410.0, 330457.0, 181808.0, 37724.0, 299534.0, 505436.0, 57800.0, 211672.0, 12444.0, 12445.0, 181812.0, 260513.0, 424619.0, 324852.0, 456165.0, 277834.0, 475557.0, 48034.0, 17578.0, 102207.0, 248507.0, 135397.0, 240832.0, 109445.0, 299536.0, 122917.0, 206647.0, 27205.0, 122917.0, 269149.0, 1865.0, 57158.0, 93456.0, 168259.0, 10192.0, 369776.0, 86868.0, 301528.0, 382597.0, 12155.0, 50620.0, 26603.0, 24428.0, 49051.0, 354912.0, 420817.0, 49026.0, 68721.0, 424694.0, 10193.0, 99861.0, 68718.0, 68718.0, 484482.0, 49047.0, 344830.0, 339964.0, 338952.0, 435259.0, 38757.0, 38277.0, 182219.0, 459151.0, 24021.0, 527729.0, 281957.0, 10198.0, 337339.0, 99770.0, 41211.0, 417859.0, 119450.0, 293660.0, 328111.0, 278927.0, 284054.0, 166426.0, 434355.0, 135397.0, 50619.0, 398929.0, 321612.0, 335797.0, 278154.0, 325844.0, 325844.0, 127380.0, 82702.0, 353486.0, 299537.0, 166428.0, 80321.0, 112198.0, 127585.0, 297802.0, 172385.0, 512200.0, 61791.0, 382591.0, 382591.0, 98205.0, 283995.0, 131631.0, 429617.0, 375804.0, 46332.0, 331836.0, 294254.0, 101299.0, 42949.0, 198663.0, 341174.0, 11324.0, 22954.0, 269148.0, 190859.0, 400155.0, 74643.0, 45269.0, 432068.0, 353081.0, 106646.0, 20352.0, 75656.0, 204668.0, 170522.0, 82992.0, 271110.0, 49013.0, 382511.0, 190880.0, 82675.0, 319341.0, 281338.0, 70160.0, 36970.0, 41411.0, 198663.0, 81188.0, 353081.0, 542830.0, 116149.0, 41513.0, 337167.0, 337167.0, 260514.0, 105864.0, 313369.0, 136799.0, 420809.0, 133469.0, 283366.0, 157336.0, 49444.0, 466272.0, 335988.0, 44214.0, 260346.0, 383498.0, 140300.0, 10138.0, 1930.0, 374720.0, 286217.0, 82992.0, 284053.0, 420817.0, 45243.0, 209112.0, 77950.0, 432613.0, 277368.0, 72190.0, 364689.0, 384018.0, 384018.0, 384018.0, 384018.0, 157350.0, 458534.0, 458534.0, 353081.0, 71157.0, 280391.0, 167613.0, 329996.0, 118340.0, 20662.0, 10528.0, 46195.0, 360920.0, 76341.0, 262551.0, 76338.0, 80015.0, 49519.0, 335988.0, 459616.0, 404368.0, 263115.0, 270946.0, 429617.0, 51447.0, 166428.0, 429617.0, 49521.0, 159824.0, 89899.0, 246320.0, 335983.0, 436969.0, 412117.0, 333339.0, 41513.0, 346364.0, 57243.0, 383869.0, 297762.0, 127585.0, 10528.0, 62211.0, 41154.0, 157350.0, 579245.0, 127585.0, 490132.0, 430424.0, 430424.0, 102651.0, 399579.0, 332562.0, 451500.0, 76170.0, 612368.0, 284052.0, 126125.0, 431580.0, 58595.0, 578489.0, 62213.0, 277839.0, 375798.0, 97365.0, 109439.0, 252607.0, 271110.0, 210577.0, 87101.0, 121856.0, 346648.0, 139156.0, 446894.0, 70981.0, 248705.0, 342473.0, 47964.0, 172106.0, 587301.0, 66118.0, 167613.0, 41513.0, 219318.0, 98566.0, 98566.0, 381288.0, 102899.0, 480530.0, 70160.0, 77459.0, 10195.0, 177572.0, 469274.0, 447404.0, 151960.0, 151960.0, 207703.0, 207703.0, 82690.0, 126125.0, 183836.0, 487476.0, 245775.0, 245775.0, 35552.0, 250349.0, 68728.0, 64690.0, 399121.0, 484468.0, 250546.0, 206408.0, 400650.0, 197950.0, 68724.0, 323020.0, 375950.0, 37686.0, 474350.0, 37799.0, 157350.0, 324668.0, 35025.0, 27576.0, 120467.0, 120467.0, 75258.0, 138843.0, 140870.0, 392044.0, 160588.0, 160588.0, 94196.0, 88794.0, 589982.0, 498248.0, 335988.0, 87101.0, 44269.0, 75780.0, 127585.0, 348350.0, 222297.0, 44264.0, 62580.0, 173185.0, 398920.0, 273169.0, 198916.0, 72105.0, 68734.0, 382593.0, 399055.0, 75612.0, 37786.0, 377799.0, 274870.0, 450465.0, 44826.0, 434616.0, 39451.0, 82700.0, 61672.0, 338970.0, 589976.0, 44896.0, 332794.0, 137113.0, 52043.0, 225574.0, 392142.0, 335984.0, 20526.0, 56415.0, 51071.0, 121875.0, 265177.0, 227783.0, 32856.0, 265228.0, 34544.0, 363676.0, 156236.0, 136403.0, 138843.0, 146233.0, 254128.0, 419430.0, 214756.0, 359724.0, 421447.0, 431693.0, 37645.0, 136294.0, 424783.0, 452187.0, 44155.0, 169020.0, 39254.0, 39254.0, 170689.0, 384371.0, 23168.0, 139649.0, 11439.0, 287947.0, 41446.0, 352157.0, 44833.0, 126125.0, 271110.0, 229297.0, 202575.0, 103327.0, 175112.0, 53010.0, 52259.0, 419704.0, 222935.0, 159121.0, 528773.0, 430365.0, 58043.0, 49529.0, 76726.0, 68726.0, 123229.0, 463858.0, 484751.0, 332210.0, 48138.0, 329809.0, 23047.0, 302348.0, 16866.0, 52449.0, 339397.0, 348713.0, 116745.0, 116745.0, 479455.0, 160564.0, 152780.0, 271724.0, 41630.0, 51739.0, 47971.0, 158852.0, 569814.0, 453405.0, 509364.0, 173897.0, 341392.0, 402900.0, 207932.0, 82990.0, 369780.0, 387592.0, 566454.0, 209355.0, 126319.0, 59967.0, 428756.0, 381284.0, 54138.0, 76493.0, 51876.0, 135281.0, 135281.0, 38031.0, 440161.0, 199549.0, 157820.0, 509730.0, 522681.0, 458302.0, 37710.0, 451945.0, 200462.0, 303858.0, 489418.0, 581472.0, 339403.0, 37832.0, 401981.0, 53457.0, 393559.0, 48171.0, 72559.0, 510452.0, 478820.0, 478820.0, 50848.0, 72571.0, 241875.0, 510465.0, 44912.0, 10263.0, 332872.0, 613349.0, 324857.0, 53844.0, 41733.0, 57165.0, 157353.0, 41436.0, 519106.0, 519106.0, 81342.0, 382595.0, 228150.0, 86837.0, 78476.0, 58224.0, 369781.0, 504608.0, 463861.0, 65057.0, 445651.0, 328387.0, 57695.0, 329805.0, 342281.0, 61667.0, 50845.0, 378236.0, 156022.0, 39513.0, 592480.0, 68713.0, 68713.0, 65233.0, 432087.0, 57212.0, 574861.0, 257344.0, 18191.0, 427348.0, 45612.0, 59859.0, 329819.0, 365045.0, 333549.0, 364051.0, 113594.0, 467482.0, 398939.0, 454640.0, 46529.0, 43347.0, 43347.0, 39538.0, 448779.0, 375809.0, 515195.0, 82682.0, 205220.0, 59961.0, 73579.0, 11652.0, 322125.0, 38167.0, 447200.0, 214087.0, 426962.0, 432618.0, 447332.0, 583268.0, 168672.0, 413644.0, 421456.0, 43593.0, 103731.0, 244786.0, 377263.0, 337674.0, 314402.0, 49017.0, 146216.0, 204082.0, 100381.0, 305387.0, 495673.0, 65759.0, 463053.0, 737342.0, 62214.0, 364137.0, 364137.0, 443398.0, 462979.0, 378111.0, 50014.0, 314365.0, 141581.0, 38060.0, 71688.0, 62835.0, 360994.0, 198184.0, 122081.0, 469055.0, 38961.0, 492550.0, 382509.0, 316029.0, 199661.0, 289171.0, 475303.0, 338967.0, 320006.0, 49510.0, 49510.0, 428078.0, 60650.0, 490450.0, 532938.0, 87502.0, 547388.0, 68178.0, 68178.0, 23629.0, 50359.0, 272435.0, 73532.0, 283726.0, 301337.0, 227348.0, 59861.0, 302699.0, 371865.0, 100830.0, 81836.0, 393764.0, 55721.0, 303483.0, 468207.0, 358725.0, 34851.0, 37534.0, 515911.0, 187017.0, 334533.0, 51072.0, 329724.0, 204198.0, 86829.0, 277432.0, 99579.0, 50544.0, 117251.0, 348025.0, 369784.0, 289151.0, 238636.0, 298250.0, 469052.0, 80278.0, 41273.0, 486521.0, 375900.0, 225886.0, 286565.0, 63831.0, 390043.0, 495671.0, 97630.0, 152737.0, 138832.0, 204436.0, 86391.0, 48231.0, 173897.0, 59145.0, 570260.0, 58858.0, 308266.0, 87421.0, 12573.0, 221902.0, 221902.0, 83666.0, 130055.0, 593475.0, 134673.0, 302401.0, 82525.0, 77951.0, 85546.0, 280092.0, 77878.0, 419772.0, 68737.0, 427347.0, 522369.0, 925872.0, 191714.0, 53404.0, 39210.0, 172391.0, 346685.0, 511987.0, 53866.0, 72331.0, 72331.0, 170687.0, 334541.0, 305455.0, 258480.0, 333371.0, 482712.0, 248611.0, 44943.0, 370567.0, 136797.0, 79108.0, 398947.0, 215303.0, 376866.0, 44009.0, 77462.0, 129112.0, 49018.0, 27579.0, 570132.0, 137094.0, 262958.0, 77987.0, 152601.0, 589985.0, 256913.0, 109424.0, 437425.0, 489415.0, 273481.0, 263281.0, 259694.0, 82633.0, 83542.0, 487004.0, 37638.0, 76025.0, 393717.0, 341013.0, 343702.0, 24438.0, 96936.0, 469056.0, 332812.0, 199914.0, 425336.0, 273895.0, 313297.0, 25376.0, 319340.0, 38408.0, 80274.0, 200823.0, 438347.0, 443401.0, 82507.0, 253239.0, 204765.0, 77460.0, 277231.0, 393945.0, 83389.0, 62215.0, 52264.0, 228326.0, 321258.0, 370755.0, 83801.0, 498249.0, 402907.0, 245891.0, 486520.0, 605015.0, 399174.0, 340361.0, 400617.0, 295087.0, 279545.0, 574097.0, 157690.0, 270343.0, 481157.0, 274855.0, 314095.0, 348060.0, 358430.0, 520318.0, 451955.0, 280092.0, 280092.0, 267804.0, 294463.0, 498247.0, 29963.0, 382503.0, 404733.0, 504562.0, 353070.0, 310593.0, 290250.0, 595867.0, 517814.0, 451657.0, 417678.0, 200645.0, 267860.0, 429189.0, 353491.0, 152532.0, 484747.0, 411626.0, 384680.0, 298312.0, 440355.0, 381353.0, 87093.0, 8952.0, 121793.0, 13546.0, 187672.0, 516999.0, 10313.0, 76487.0, 10197.0, 10315.0, 369779.0, 339988.0, 420950.0, 49014.0, 359538.0, 71179.0, 270342.0, 346910.0, 887128.0, 381262.0, 381262.0, 401246.0, 44115.0, 261392.0, 262117.0, 261023.0, 121873.0, 85373.0, 85872.0, 78478.0, 383807.0, 266537.0, 50839.0, 192136.0, 280511.0, 376659.0, 430447.0, 287495.0, 559401.0, 76494.0, 504603.0, 291984.0, 150117.0, 374475.0, 304357.0, 499151.0, 241239.0, 324552.0, 7978.0, 258435.0, 102969.0, 143567.0, 398818.0, 136400.0, 535581.0, 639250.0, 572521.0, 384112.0, 446044.0, 467675.0, 274858.0, 121702.0, 407448.0, 209357.0, 505940.0, 45958.0, 361243.0, 264656.0, 216282.0, 142096.0, 152599.0, 173897.0, 393729.0, 7445.0, 182246.0, 582881.0, 254473.0, 543633.0, 307663.0, 345920.0, 302946.0, 190853.0, 53980.0, 296524.0, 57276.0, 245700.0, 152603.0, 602283.0, 22970.0, 118289.0, 255824.0, 531428.0, 266082.0, 445768.0, 110397.0, 391713.0, 502416.0, 437399.0, 398933.0, 283445.0, 46738.0, 109261.0, 46955.0, 73585.0, 100042.0, 201085.0, 395834.0, 490462.0, 64688.0, 118293.0, 52350.0, 119281.0, 132232.0, 446170.0, 223946.0, 499722.0, 290512.0, 88284.0, 549053.0, 214418.0, 119193.0, 226109.0, 82654.0, 681985.0, 146198.0, 77458.0, 215211.0, 7980.0, 317940.0, 53456.0, 77930.0, 394161.0, 439155.0, 41515.0, 277685.0, 314388.0, 65229.0, 26428.0, 510456.0, 462503.0, 242512.0, 93847.0, 116741.0, 31175.0, 100241.0, 396535.0, 336805.0, 38365.0, 254470.0, 120905.0, 449443.0, 204046.0, 95191.0, 512196.0, 512196.0, 123221.0, 373960.0, 567748.0, 198277.0, 490422.0, 202215.0, 313055.0, 452188.0, 11699.0, 515820.0, 48303.0, 197082.0, 602971.0, 415842.0, 394259.0, 395452.0, 218993.0, 197629.0, 69668.0, 575458.0, 37430.0, 485166.0, 245703.0, 458252.0, 119283.0, 44737.0, 592807.0, 286595.0, 138697.0, 85449.0, 40194.0, 42684.0, 121986.0, 115782.0, 501170.0, 477489.0, 85350.0, 130987.0, 136795.0, 423646.0, 125623.0, 50348.0, 55846.0, 338766.0, 476299.0, 119675.0, 76216.0, 37655.0, 88273.0, 151826.0, 366564.0, 66122.0, 339259.0, 82696.0, 64686.0, 112336.0, 369770.0, 42722.0, 182560.0, 365997.0, 190955.0, 49021.0, 437316.0, 74119.0, 64689.0, 254320.0, 377154.0, 340666.0, 351454.0, 188207.0, 452773.0, 614704.0, 428558.0, 133805.0, 69157.0, 122192.0, 529790.0, 435129.0, 246860.0, 463272.0, 331781.0, 70868.0, 57311.0, 433919.0, 556950.0, 331112.0, 582906.0, 53596.0, 521092.0, 27573.0, 304031.0, 26388.0, 513386.0, 23742.0, 80035.0, 56002.0, 392794.0, 186991.0, 123235.0, 19901.0, 340837.0, 37707.0, 68727.0, 451713.0, 403300.0, 544404.0, 53930.0, 437739.0, 38357.0, 514577.0, 589978.0, 189019.0, 25793.0, 209451.0, 315575.0, 347375.0, 74308.0, 426825.0, 56405.0, 372607.0, 50158.0, 582883.0, 270400.0, 381351.0, 266856.0, 86687.0, 438799.0, 84334.0, 417384.0, 157849.0, 137093.0, 351211.0, 482114.0, 324542.0, 336811.0, 38073.0, 396461.0, 485189.0, 68722.0, 92424.0, 74513.0, 115348.0, 113160.0, 291520.0, 473325.0, 181886.0, 408024.0, 345775.0, 169917.0, 210860.0, 336050.0, 279550.0, 64720.0, 243940.0, 374251.0, 309886.0, 380830.0, 394684.0, 55347.0, 82817.0, 137182.0, 40264.0, 408550.0, 59112.0, 43920.0, 337107.0, 439152.0, 59440.0, 353616.0, 264999.0, 149871.0, 459992.0, 225719.0, 341742.0, 149509.0, 192149.0, 199977.0, 38579.0, 107444.0, 450179.0, 187022.0, 452406.0, 65055.0, 178513.0, 458594.0, 278646.0, 397243.0, 78480.0, 204922.0, 353069.0, 53776.0, 111190.0, 584350.0, 288587.0, 129953.0, 54054.0, 209249.0, 402897.0, 451679.0, 66120.0, 155887.0, 58151.0, 46837.0, 103328.0, 539228.0, 395769.0, 519141.0, 484247.0, 454652.0, 23631.0, 265189.0, 537965.0, 515816.0, 228194.0, 801703.0, 110957.0, 392124.0, 400020.0, 59108.0, 395458.0, 553478.0, 252512.0, 500860.0, 393407.0, 451480.0, 84174.0, 499723.0, 41210.0, 344475.0, 377273.0, 446039.0, 63492.0, 423899.0, 399360.0, 127856.0, 71469.0, 188765.0, 430916.0, 394117.0, 321697.0, 445571.0, 384727.0, 66682.0, 432614.0, 73567.0, 429662.0, 483184.0, 342149.0, 34653.0, 55003.0, 400711.0, 48289.0, 442266.0, 574207.0, 158011.0, 57157.0, 145135.0, 310569.0, 87492.0, 456768.0, 44129.0, 434555.0, 204709.0, 374671.0, 586940.0, 430528.0, 174751.0, 454992.0, 103717.0, 93856.0, 99508.0, 399170.0, 399170.0, 483983.0, 266396.0, 77561.0, 415032.0, 167073.0, 384682.0, 82390.0, 203145.0, 417870.0, 186971.0, 356161.0, 296360.0, 97370.0, 254904.0, 167810.0, 266040.0, 529784.0, 493899.0, 286111.0, 393519.0, 456162.0, 389015.0, 323432.0, 53487.0, 230731.0, 46207.0, 89705.0, 86838.0, 415034.0, 415034.0, 446038.0, 460059.0, 282296.0, 510469.0, 61901.0, 42297.0, 592798.0, 184020.0, 56743.0, 559729.0, 205048.0, 512056.0, 31011.0, 37414.0, 75233.0, 127864.0, 506596.0, 106747.0, 426830.0, 443119.0, 379149.0, 24424.0, 284293.0, 301365.0, 184352.0, 355277.0, 161074.0, 127489.0, 48838.0, 318781.0, 74879.0, 94973.0, 87504.0, 471506.0, 474313.0, 203715.0, 46838.0, 559501.0, 171274.0, 204768.0, 449176.0, 416186.0, 446021.0, 466703.0, 468284.0, 315664.0, 444397.0, 216156.0, 424344.0, 252773.0, 492452.0, 19899.0, 537021.0, 180433.0, 470114.0, 310131.0, 17352.0, 238781.0, 380225.0, 270303.0, 69106.0, 378029.0, 239566.0, 41402.0, 369464.0, 88005.0, 42058.0, 499726.0, 510460.0, 326874.0, 432622.0, 290764.0, 60599.0, 279579.0, 86825.0, 523703.0, 362571.0, 369772.0, 817023.0, 402298.0, 434273.0, 521777.0, 582873.0, 188598.0, 103620.0, 264401.0, 511404.0, 49526.0, 570128.0, 486519.0, 446037.0, 446037.0, 204853.0, 3469.0, 502682.0, 491473.0, 468224.0, 25769.0, 416364.0, 530385.0, 257724.0, 505747.0, 22907.0, 429200.0, 487786.0, 263472.0, 74106.0, 46705.0, 613911.0, 301351.0, 351044.0, 401200.0, 186992.0, 414372.0, 340357.0, 373473.0, 376290.0, 453352.0, 891954.0, 523172.0, 144336.0, 222230.0, 446178.0, 383709.0, 534768.0, 242828.0, 83899.0, 129670.0, 122089.0, 137370.0, 39013.0, 528668.0, 429471.0, 429471.0, 94348.0, 391663.0, 181283.0, 589181.0, 134722.0, 43479.0, 595985.0, 352188.0, 45256.0, 465914.0, 59490.0, 283708.0, 1567.0, 204762.0, 223954.0, 38543.0, 415010.0, 22971.0, 407201.0, 114750.0, 413837.0, 123018.0, 412203.0, 570701.0, 82327.0, 536510.0, 129431.0, 489170.0, 576017.0, 44629.0, 316152.0, 586874.0, 114150.0, 61374.0, 300671.0, 575557.0, 78381.0, 60422.0, 399366.0, 377853.0, 228492.0, 299245.0, 71859.0, 205588.0, 110160.0, 393457.0, 331113.0, 332283.0, 109391.0, 77016.0, 525916.0, 74848.0, 67762.0, 12572.0, 401847.0, 512865.0, 67509.0, 874606.0, 446130.0, 537651.0, 139725.0, 491392.0, 86828.0, 534373.0, 339877.0, 165420.0, 258363.0, 430005.0, 415036.0, 458253.0, 259460.0, 446159.0, 154400.0, 287424.0, 300693.0, 589230.0, 570137.0, 85435.0, 56959.0, 83390.0, 336212.0, 446131.0, 129966.0, 617986.0, 543636.0, 377798.0, 268523.0, 478860.0, 377276.0, 109418.0, 68812.0, 500664.0, 369557.0, 180299.0, 180299.0, 37667.0, 271714.0, 337677.0, 434775.0, 209350.0, 431530.0, 28211.0, 453278.0, 257381.0, 455207.0, 392820.0, 68280.0, 339408.0, 455588.0, 542828.0, 534371.0, 482981.0, 253626.0, 569188.0, 98357.0, 98357.0, 71559.0, 97434.0, 446171.0, 267192.0, 249164.0, 348964.0, 481432.0, 79728.0, 400579.0, 200346.0, 59507.0, 109417.0, 187667.0, 256917.0, 397074.0, 57403.0, 112555.0, 399248.0, 89287.0, 582874.0, 209276.0, 198130.0, 37950.0, 419478.0, 69798.0, 87558.0, 27583.0, 458956.0, 244088.0, 114535.0, 47261.0, 356381.0, 413998.0, 381289.0, 812398.0, 371638.0, 102362.0, 255319.0, 77953.0, 501633.0, 115821.0, 73872.0, 452016.0, 377275.0, 286101.0, 244509.0, 482710.0, 200830.0, 618326.0, 84892.0, 179150.0, 275601.0, 288036.0, 490594.0, 575479.0, 50456.0, 615821.0, 63976.0, 453356.0, 190870.0, 247577.0, 330298.0, 112377.0, 66128.0, 66128.0, 360225.0, 406761.0, 334991.0, 43409.0, 465871.0, 294458.0, 573683.0, 374464.0, 351186.0, 179109.0, 429191.0, 454294.0, 795230.0, 164251.0, 89065.0, 123105.0, 539885.0, 47760.0, 463633.0, 319888.0, 487680.0, 320001.0, 394262.0, 23514.0, 375898.0, 46221.0, 392011.0, 369192.0, 293310.0, 102752.0, 756361.0, 405775.0, 489840.0, 331114.0, 213681.0, 355065.0, 504605.0, 315865.0, 502422.0, 80038.0, 503919.0, 62176.0, 73873.0, 28118.0, 132344.0, 459966.0, 27586.0, 459960.0, 325385.0, 203814.0, 349105.0, 493913.0, 951576.0, 380622.0, 246127.0, 243233.0, 348375.0, 23172.0, 152747.0, 944945.0, 775.0, 116377.0, 559525.0, 336197.0, 408509.0, 128070.0, 203739.0, 267970.0, 451915.0, 33511.0, 78363.0, 446040.0, 41123.0, 99389.0, 384212.0, 399402.0, 510641.0, 245692.0, 197783.0, 377151.0, 63310.0, 492998.0, 44096.0, 439151.0, 287509.0, 392127.0, 270457.0, 329815.0, 59065.0, 110146.0, 561318.0, 223702.0, 264660.0, 432226.0, 266080.0, 342737.0, 496967.0, 475928.0, 376530.0, 188166.0, 166428.0, 424505.0, 333669.0, 291270.0, 71880.0, 500902.0, 284280.0, 436340.0, 285387.0, 347477.0, 54093.0, 321974.0, 103740.0, 208134.0, 285394.0, 254679.0, 41479.0, 425218.0, 380623.0, 74306.0, 868575.0, 152742.0, 328587.0, 270646.0, 433694.0, 100271.0, 432625.0, 126321.0, 300673.0, 27585.0, 413778.0, 443463.0, 399790.0, 484638.0, 130739.0, 10665.0, 180644.0, 214099.0, 388399.0, 506421.0, 310307.0, 72721.0, 301355.0, 270302.0, 52587.0, 161073.0, 507076.0, 407250.0, 472451.0, 57602.0, 48508.0, 570258.0, 50357.0, 45061.0, 759297.0, 57829.0, 271718.0, 84336.0, 77560.0, 596860.0, 46206.0, 252178.0, 109414.0, 37905.0, 525427.0, 339568.0, 58764.0, 57390.0, 285023.0, 127880.0, 253686.0, 136424.0, 158990.0, 525554.0, 270920.0, 396917.0, 157845.0, 330697.0, 453364.0, 454458.0, 48392.0, 87818.0, 679108.0, 582944.0, 79070.0, 798143.0, 266061.0, 247319.0, 337730.0, 262009.0, 96821.0, 43609.0, 411638.0, 25941.0, 63578.0, 51276.0, 98277.0, 127560.0, 130099.0, 459556.0, 329833.0, 331797.0, 27569.0, 163736.0, 186976.0, 284290.0, 284689.0, 314578.0, 157825.0, 89455.0, 449754.0, 126326.0, 585381.0, 372770.0, 399057.0, 172520.0, 50837.0, 133246.0, 565720.0, 51814.0, 480647.0, 57401.0, 312669.0, 146592.0, 22832.0, 428449.0, 478795.0, 147798.0, 223706.0, 81025.0, 208837.0, 228152.0, 426256.0, 434131.0, 325348.0, 323675.0, 384726.0, 245855.0, 441646.0, 129432.0, 313922.0, 511468.0, 375487.0, 56174.0, 534874.0, 568389.0, 398173.0, 254201.0, 537180.0, 274483.0, 45649.0, 510475.0, 330333.0, 432090.0, 49020.0, 48414.0, 425665.0, 427890.0, 590088.0, 501590.0, 428584.0, 353460.0, 329682.0, 189021.0, 152825.0, 344120.0, 57393.0, 190851.0, 459963.0, 268115.0, 413652.0, 453358.0, 112592.0, 478508.0, 912041.0, 281968.0, 486101.0, 422566.0, 319356.0, 214210.0, 316062.0, 558978.0, 76543.0, 76617.0, 415005.0, 378108.0, 41283.0, 156173.0, 25196.0, 91052.0, 260646.0, 102001.0, 33273.0, 54518.0, 265349.0, 495271.0, 619403.0, 196398.0, 171582.0, 428226.0, 85454.0, 48243.0, 53399.0, 468213.0, 32084.0, 237876.0, 43434.0, 359770.0, 319348.0, 36956.0, 484594.0, 361255.0, 479261.0, 328589.0, 444539.0, 186729.0, 474444.0, 44961.0, 468212.0, 53485.0, 39800.0, 287904.0, 155890.0, 206277.0, 109154.0, 278236.0, 414001.0, 319337.0, 427214.0, 496570.0, 57018.0, 493483.0, 110969.0, 476968.0, 89733.0, 44241.0, 369594.0, 298721.0, 500852.0, 417670.0, 267999.0, 351037.0, 196405.0, 355234.0, 428753.0, 451985.0, 579273.0, 340485.0, 449757.0, 412204.0, 308639.0, 160115.0, 121983.0, 340487.0, 285848.0, 760926.0, 125342.0, 371859.0, 61891.0, 309245.0, 436120.0, 53389.0, 43943.0, 253684.0, 467679.0, 91186.0, 38542.0, 209262.0, 58699.0, 254772.0, 416574.0, 188222.0, 94904.0, 302627.0, 157354.0, 122198.0, 490862.0, 31007.0, 336663.0, 609917.0, 45595.0, 346780.0, 304126.0, 63946.0, 209385.0, 12166.0, 372394.0, 82485.0, 295314.0, 376865.0, 45127.0, 871949.0, 287574.0, 571650.0, 49001.0, 458807.0, 136582.0, 472674.0, 80079.0, 366104.0, 436352.0, 374452.0, 544522.0, 216769.0, 461615.0, 348193.0, 336655.0, 192767.0, 379691.0, 192132.0, 326094.0, 184992.0, 396253.0, 50365.0, 462146.0, 565403.0, 86835.0, 440418.0, 512916.0, 28417.0, 474298.0, 216457.0, 394741.0, 507256.0, 393520.0, 401898.0, 566236.0, 442718.0, 430007.0, 563309.0, 55836.0, 59582.0, 289035.0, 52474.0, 393517.0, 134781.0, 114982.0, 226788.0, 74795.0, 358893.0, 159014.0, 874961.0, 574434.0, 455200.0, 413767.0, 484410.0, 453272.0, 471507.0, 145361.0, 310567.0, 451044.0, 283700.0, 345594.0, 126328.0, 270401.0, 243684.0, 470643.0, 266031.0, 57387.0, 415665.0, 113947.0, 449856.0, 117646.0, 467548.0, 195173.0, 40817.0, 85542.0, 284276.0, 425720.0, 543580.0, 837308.0, 216789.0, 28053.0, 392788.0, 61826.0, 232572.0, 422949.0, 358403.0, 474353.0, 283698.0, 254302.0, 36940.0, 550473.0, 277713.0, 484428.0, 453277.0, 550958.0, 534667.0, 496212.0, 517114.0, 76696.0, 364911.0, 327040.0, 326285.0, 63849.0, 30312.0, 294992.0, 354275.0, 554311.0, 396924.0, 82684.0, 158091.0, 324687.0, 324807.0, 186988.0, 174368.0, 121640.0, 54083.0, 446164.0, 418798.0, 433627.0, 470878.0, 49797.0, 299780.0, 431819.0, 49850.0, 534338.0, 291351.0, 659586.0, 485098.0, 76247.0, 347026.0, 397010.0, 438488.0, 134908.0, 475855.0, 174671.0, 137372.0, 268207.0, 89456.0, 161078.0, 319342.0, 440918.0, 463473.0, 356296.0, 391138.0, 597088.0, 157824.0, 324560.0, 8075.0, 611241.0, 81621.0, 574011.0, 222581.0, 84329.0, 52369.0, 216783.0, 617299.0, 336203.0, 138859.0, 72207.0, 191458.0, 355998.0, 293271.0, 392791.0, 378698.0, 549350.0, 179100.0, 167502.0, 179538.0, 446101.0, 72355.0, 40827.0, 51999.0, 403639.0, 107391.0, 93578.0, 424781.0, 302688.0, 193077.0, 424965.0, 452970.0, 332160.0, 80440.0, 339186.0, 338632.0, 361705.0, 28874.0, 479379.0, 40798.0, 336207.0, 619263.0, 169817.0, 212721.0, 359678.0, 254905.0, 518495.0, 259045.0, 81167.0, 84188.0, 74725.0, 504585.0, 606066.0, 391714.0, 118354.0, 295699.0, 347201.0, 103750.0, 80591.0, 186970.0, 123506.0, 259963.0, 498743.0, 374466.0, 255905.0, 286599.0, 171298.0, 22538.0, 75229.0, 256962.0, 54521.0, 283601.0, 450766.0, 124461.0, 517940.0, 164122.0, 197772.0, 482948.0, 81401.0, 515353.0, 413362.0, 517991.0, 58633.0, 4786.0, 157386.0, 58219.0, 440102.0, 123375.0, 40807.0, 212716.0, 489930.0, 519223.0, 272548.0, 382455.0, 393521.0, 46829.0, 51735.0, 400114.0, 318922.0, 314385.0, 442267.0, 418670.0, 271683.0, 214086.0, 157832.0, 108322.0, 517987.0, 113148.0, 86820.0, 203788.0, 412988.0, 517982.0, 426460.0, 258588.0, 306482.0, 89301.0, 268100.0, 455108.0, 202087.0, 121872.0, 366080.0, 116953.0, 434773.0, 519185.0, 354288.0, 534622.0, 44040.0, 266036.0, 261860.0, 309299.0, 395993.0, 348892.0, 127374.0, 39053.0, 410678.0, 432527.0, 326382.0, 87440.0, 36811.0, 516780.0, 167668.0, 348678.0, 293767.0, 334521.0, 493099.0, 40175.0, 21345.0, 191718.0, 487416.0, 87499.0, 38448.0, 429637.0, 89623.0, 248774.0, 44977.0, 571473.0, 112380.0, 25195.0, 132316.0, 427955.0, 519120.0, 400148.0, 15371.0, 150747.0, 55725.0, 549559.0, 413601.0, 210479.0, 403450.0, 168530.0, 59931.0, 62206.0, 352162.0, 50318.0, 146223.0, 331588.0, 419709.0, 2588.0, 505706.0, 300425.0, 161728.0, 80801.0, 94838.0, 41602.0, 392803.0, 408542.0, 280075.0, 446696.0, 360288.0, 250219.0, 428754.0, 335663.0, 333674.0, 216790.0, 52850.0, 553084.0, 45094.0, 38319.0, 301846.0, 246011.0, 221189.0, 315868.0, 51591.0, 468198.0, 77805.0, 287719.0, 75622.0, 413658.0, 552088.0, 397113.0, 854868.0, 58496.0, 382127.0, 23759.0, 556271.0, 496339.0, 46458.0, 592776.0, 58884.0, 62728.0, 436391.0, 176794.0, 287903.0, 414202.0, 78571.0, 362045.0, 611748.0, 45272.0, 59860.0, 422613.0, 200341.0, 219055.0, 493900.0, 120185.0, 158936.0, 258378.0, 23023.0, 226648.0, 643534.0, 50725.0, 527699.0, 576121.0, 503742.0, 346681.0, 34563.0, 15941.0, 315840.0, 205601.0, 266639.0, 420622.0, 23706.0, 228205.0, 319921.0, 534624.0, 43931.0, 46689.0, 611594.0, 401546.0, 537880.0, 296103.0, 111943.0, 534075.0, 245706.0, 279748.0, 25704.0, 232175.0, 362140.0, 44754.0, 503129.0, 175541.0, 539456.0, 437557.0, 88042.0, 497814.0, 302616.0, 82505.0, 397722.0, 76489.0, 253254.0, 64678.0, 550485.0, 108476.0, 445793.0, 596650.0, 39135.0, 192134.0, 52067.0, 589311.0, 235984.0]

In [55]:
list_genres=[]
for i in tmdb_id:
    try:
        movie=tmdb.Movies(i)
        response = movie.info()
        genres=movie.genres
        list_genres.append(genres)
    except:
        list_genres.append('Not found')

In [43]:
    movie=tmdb.Movies(77338.0)
    response = movie.info()
    genres=movie.genres
    list_genres.append(genres)

In [48]:
    >>> movie = tmdb.Movies(338952.0)
    >>> response = movie.info()
    >>> movie.title
    'The Matrix'
    >>> movie.genres

[{'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 18, 'name': 'Drama'}]

In [45]:
len(list_genres)

62

In [47]:
tmdb_id[63]

338952.0

In [52]:
len(list_genres)

2400

In [53]:
list_genres_saved=list_genres

In [56]:
len(list_genres)

2407

In [57]:
len(tmdb_id)

2407

In [60]:
import pandas as pd
movie_genres=pd.DataFrame({'tmdb_id':tmdb_id,'genres':list_genres})

In [73]:
movie_genres.to_csv(r'C:\Users\lenovo\Desktop\ironhack\FINAL PROJECT\french-box-office\data\movie_genres.csv')

In [62]:
movie_genres.head()

    tmdb_id                                             genres
0   77338.0  [{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...
1  262391.0                     [{'id': 35, 'name': 'Comedy'}]
2  140607.0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...
3  420818.0  [{'id': 12, 'name': 'Adventure'}, {'id': 10751...
4   52077.0                     [{'id': 35, 'name': 'Comedy'}]

In [63]:
movie_genres['genres'].apply(pd.Series)

,0,1,2,3,4,5
0,"{'id': 18, 'name': 'Drama'}","{'id': 35, 'name': 'Comedy'}",NaN,NaN,NaN,NaN
1,"{'id': 35, 'name': 'Comedy'}",NaN,NaN,NaN,NaN,NaN
2,"{'id': 28, 'name': 'Action'}","{'id': 12, 'name': 'Adventure'}","{'id': 878, 'name': 'Science Fiction'}","{'id': 14, 'name': 'Fantasy'}",NaN,NaN
3,"{'id': 12, 'name': 'Adventure'}","{'id': 10751, 'name': 'Family'}","{'id': 16, 'name': 'Animation'}",NaN,NaN,NaN
4,"{'id': 35, 'name': 'Comedy'}",NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2402,"{'id': 14, 'name': 'Fantasy'}","{'id': 18, 'name': 'Drama'}","{'id': 10749, 'name': 'Romance'}",NaN,NaN,NaN
2403,"{'id': 35, 'name': 'Comedy'}","{'id': 80, 'name': 'Crime'}","{'id': 18, 'name': 'Drama'}",NaN,NaN,NaN
2404,"{'id': 35, 'name': 'Comedy'}",NaN,NaN,NaN,NaN,NaN
2405,"{'id': 35, 'name': 'Comedy'}",NaN,NaN,NaN,NaN,NaN
2406,"{'id': 18, 'name': 'Drama'}","{'id': 10749, 'name': 'Romance'}",NaN,NaN,NaN,NaN

In [65]:
movie_genres[['genre1','genre2','genre3','genre4','genre5','genre6']]=movie_genres['genres'].apply(pd.Series)

In [67]:
movie_genres.drop(columns=['genres','genre4','genre5','genre6'],inplace=True)

In [72]:
for column in ['genre1','genre2','genre3']:
    movie_genres[column]=movie_genres[column].apply(lambda x: x['name'] if type(x)==dict else x)